name: Test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Copy .env
        run: |
          cp .env.example .env
      - name: Composer install
        run: composer install -n --prefer-dist
      - name: Launch
        run: |
          ./vendor/bin/sail up -d
      - name: Generate key
        run: |
          docker-compose exec -T laravel.test php artisan key:generate
      - name: Wait for MySQL to start # https://www.pnkts.net/2020/07/27/connection-refused
        run: |
          docker-compose exec -T mysql bash -c "mysqladmin --wait --count 60 ping || exit 1"
      - name: Migrate database
        run: |
          docker-compose exec -T laravel.test php artisan migrate --seed
      - name: Test
        run: |
          docker-compose exec -T laravel.test php artisan test
